import Head from "next/head";
import Image from "next/image";

import { Input } from "@ranger/ui-theme";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Image
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        <Input />
        <footer>
          <p>Nextjs On SSL</p>
        </footer>
      </main>
    </>
  );
};

export default Home;
