import { useRef, useState } from 'react'
import {
  CopyBoard,
  CountDown,
  IntersectionScroll,
  PrintScreen,
  Resizable,
  SignatureCanvas
} from '@ranger-theme/ui'
import dynamic from 'next/dynamic'
import Head from 'next/head'

const CsvLink = dynamic(
  import('@ranger-theme/ui').then((module) => module.CsvLink),
  {
    ssr: false
  }
)
const MediaQuery = dynamic(
  import('@ranger-theme/ui').then((module) => module.MediaQuery),
  {
    ssr: false
  }
)
const Player = dynamic(
  import('@ranger-theme/ui').then((module) => module.Player),
  {
    ssr: false
  }
)

const Cart = () => {
  const componentRef = useRef<any>(null)
  const sigPadRef = useRef<any>(null)
  const [trimmedDataURL, setTrimmedDataURL] = useState<string>('')

  const csvData = [
    ['firstname', 'lastname', 'email'],
    ['Ahmed', 'Tomi', 'ah@smthing.co.com'],
    ['Raed', 'Labes', 'rl@smthing.co.com'],
    ['Yezzi', 'Min l3b', 'ymin@cocococo.com']
  ]

  const onCopy = (text: string) => {
    window.alert(text)
  }

  const onClear = () => {
    sigPadRef.current.clear()
  }

  const onTrim = () => {
    setTrimmedDataURL(sigPadRef.current.getTrimmedCanvas().toDataURL('image/png'))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="cart">
        <div>{trimmedDataURL}</div>
        <div ref={componentRef}>
          <div>
            <SignatureCanvas
              penColor="green"
              canvasProps={{ width: 500, height: 200, className: 'sigCanvas' }}
              ref={sigPadRef}
            />
            <button type="button" onClick={onClear}>
              Clear
            </button>
            <button type="button" onClick={onTrim}>
              Trim
            </button>
          </div>
          <Player
            className="react-player"
            url="https://www.youtube.com/watch?v=aL27fX5kv9U"
            width="800px"
            height="500px"
            controls
          />
          <div>
            <CountDown date={Date.now() + 10000} />
          </div>
          <CopyBoard text="hello world" onCopy={onCopy}>
            <span>Copy to clipboard</span>
          </CopyBoard>
          <div>
            <CsvLink data={csvData}>Download me</CsvLink>
          </div>
          <MediaQuery minWidth={1224}>
            <p>You are a desktop or laptop</p>
            <MediaQuery minWidth={1824}>
              <p>You also have a huge screen</p>
            </MediaQuery>
          </MediaQuery>
          <Resizable
            width={200}
            height={200}
            minConstraints={[100, 100]}
            maxConstraints={[400, 400]}
          >
            <span>Contents</span>
          </Resizable>
        </div>
        <div>
          <PrintScreen
            // eslint-disable-next-line react/no-unstable-nested-components
            trigger={() => {
              return <p>Print this out!</p>
            }}
            content={() => componentRef.current}
          />
          <IntersectionScroll>
            <div>Intersection Scroll</div>
          </IntersectionScroll>
        </div>
      </div>
    </>
  )
}

export default Cart
