import Head from 'next/head'
import Image from 'next/image'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Image src="/next.svg" alt="Next.js Logo" width={180} height={37} priority />
        </div>
      </main>
    </>
  )
}

export default Home
